// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package history

type Jobrun struct {
	ID        int64
	Jobname   string
	Jobnumber int64
	Database  string
	Query     string
	Started   string
	Status    string
}

type LastDbStatus struct {
	Database  string
	LastSeen  string
	Available int64
}

type LastFinishedJobStatus struct {
	Jobname   string
	Jobnumber int64
	LastSeen  string
	Succeeded int64
}
