name: sqlc
on: [push]
permissions:
  contents: read
  pull-requests: read
jobs:
  diff:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: sqlc-dev/setup-sqlc@v3
      with:
        sqlc-version: '1.26.0'
    - run: sqlc diff
